### ISSUE TITLE
Transition from Warcbase to AUT

### ISSUE THREAD

**Issue by ianmilligan1** [archivesunleashed/aut-docs#3]
For each page, we need to 

1. play-test the material;
2. update calls from `org.warcbase` to `io.archivesunleashed`;
3. and change references from "Warcbase" to "Archives Unleashed Toolkit" (or AUT if full name is ungainly)

Here is list of pages, bearing in mind that in #2 we decided to consolidate the four installation pages into one. 

- [ ] Analyzing-Web-Archives-with-Spark.md
- [ ] Building-and-Running-Warcbase-Under-OS-X.md
- [ ] Gephi-Converting-Site-Link-Structure-into-Dynamic-Visualization.md
- [ ] Getting-Started.md
- [ ] Installing-and-Running-Spark-under-OS-X.md
- [ ] README.md
- [ ] SUMMARY.md
- [ ] Sample-Data.md
- [ ] Spark-Analysis-of-Site-Link-Structure.md
- [ ] Spark-Collection-Analytics.md
- [ ] Spark-Extracting-Domain-Level-Plain-Text.md
- [ ] Spark-Image-Analysis.md
- [ ] Spark-Installing-Spark-Notebook-on-a-Cloud-Computer.md
- [ ] Spark-NER-Visualization.md
- [ ] Spark-Named-Entity-Recognition.md
- [ ] Spark-Network-Analysis.md
- [ ] Spark-Several-Basic-Commands.md
- [ ] Spark-Twitter-Analysis.md
- [ ] about.md

**Comment by greebie** [comment]
Playtested a few of the tutorials and revised the code, deprecated many.  It will be worth testing the tutorials, but will close this for now.
