### ISSUE TITLE
Check that tutorials work.

### ISSUE THREAD

**Issue by greebie** [archivesunleashed/aut-docs#5]
- [x] Getting Started
- [x] List of URLs
- [x] List of URLs to file
- [x] Top Level Domains Visualisation
- [x] List of Different Subdomains
- [x] Extraction of Simple Site Link Structure
- [x] Extraction of a Site Link Structure, organized by URL pattern
- [x] Grouping by Crawl Date
- [x] Exporting as TSV
- [x] Filtering by URL
- [ ] Exporting to Gephi Directly
- [x] Calculating Dynamic PageRank
- [x] ExtractGraph Explained
- [x] Extracting Domain Level Plain Text
- [x] Plain text by domain
- [x] Plain text by URL pattern
- [x] Plain text minus boilerplate
- [x] Plain text filtered by date
- [x] Plain text filtered by language
- [x] Plain text filtered by keyword
- [x] Most frequent image URLs in a collection
- [x] Most frequent images in a collection, based on MD5 hash
- [ ] Twitter analysis

**Comment by greebie** [comment]
There are a number of tutorials that seem exogenous to AUT in general.  For example, there is a Gephi tutorial that is great, but not really about using AUT.  I wonder if there is another place we could put some of these tutorials to keep things pared down to AUT?  Thoughts?

**Comment by ianmilligan1** [comment]
I think the Gephi one is the only external one eh? I think it's still worth keeping right now, as an appendix to the "Exporting to Gephi Directly" tutorial. Maybe as a separate page hidden from the main menu?

**Comment by greebie** [comment]
I think that's the main one.  I think there were a few other small paragraphs that had me wondering if they were better elsewhere.  Just worth considering.

**Comment by ianmilligan1** [comment]
Just rounding this up - are you still working on the final lessons here, @greebie, or have you hit a roadblock w/ data?

**Comment by greebie** [comment]
The only one I could not test with the example arc was the Twitter analysis.   Given that the approach is basically the same in each case, and I have yet to have a problem I think we are fine.

**Comment by ianmilligan1** [comment]
Ok, let's call them playtested then - thanks @greebie!
